// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnjc49Epok2bEAwSFncP4VQOGLXzZtaWs',
    appId: '1:41798305065:web:04a03c80c0ab3c79502338',
    messagingSenderId: '41798305065',
    projectId: 'hortapp-hortalicas',
    authDomain: 'hortapp-hortalicas.firebaseapp.com',
    storageBucket: 'hortapp-hortalicas.firebasestorage.app',
    measurementId: 'G-QP05Q6C4MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnjc49Epok2bEAwSFncP4VQOGLXzZtaWs',
    appId: '1:41798305065:android:04a03c80c0ab3c79502338',
    messagingSenderId: '41798305065',
    projectId: 'hortapp-hortalicas',
    storageBucket: 'hortapp-hortalicas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnjc49Epok2bEAwSFncP4VQOGLXzZtaWs',
    appId: '1:41798305065:ios:04a03c80c0ab3c79502338',
    messagingSenderId: '41798305065',
    projectId: 'hortapp-hortalicas',
    storageBucket: 'hortapp-hortalicas.firebasestorage.app',
    iosBundleId: 'com.example.hortalicas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnjc49Epok2bEAwSFncP4VQOGLXzZtaWs',
    appId: '1:41798305065:ios:04a03c80c0ab3c79502338',
    messagingSenderId: '41798305065',
    projectId: 'hortapp-hortalicas',
    storageBucket: 'hortapp-hortalicas.firebasestorage.app',
    iosBundleId: 'com.example.hortalicas',
  );
}
